### ISSUE TITLE
install requirements

### ISSUE THREAD

**Issue by mohamedgalalanwer** [Kitware/Danesfield#54]
I have a problem when installing the requirements, there is more than one error with persistence

 Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "C:\Users\txr\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\txr\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\txr\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\txr\AppData\Local\Temp\pip-build-env-boz3bdhg\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\txr\AppData\Local\Temp\pip-build-env-boz3bdhg\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\txr\AppData\Local\Temp\pip-build-env-boz3bdhg\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 71, in <module>
        File "<string>", line 17, in setup_package
      FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS C:\Users\txr\Documents\AI\Danesfield-master\Danesfield-master> source deactivate
source : The term 'source' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At line:1 char:1
+ source deactivate
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (source:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\txr\Documents\AI\Danesfield-master\Danesfield-master> run_danesfield.py
run_danesfield.py : The term 'run_danesfield.py' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path 
was included, verify that the path is correct and try again.
At line:1 char:1
+ run_danesfield.py
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (run_danesfield.py:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

[requirements.txt](https://github.com/Kitware/Danesfield/files/10892003/requirements.txt)

**Comment by jiaxue-ai** [comment]
what's your environment? You need to use a Linux environment or you can use docker with installing this docker image https://github.com/Kitware/Danesfield/blob/master/Dockerfile
